lib: [
  "_build/install/default/lib/spices/META"
  "_build/install/default/lib/spices/dune-package"
  "_build/install/default/lib/spices/formatter.ml"
  "_build/install/default/lib/spices/gradient.ml"
  "_build/install/default/lib/spices/opam"
  "_build/install/default/lib/spices/spices.a"
  "_build/install/default/lib/spices/spices.cma"
  "_build/install/default/lib/spices/spices.cmi"
  "_build/install/default/lib/spices/spices.cmt"
  "_build/install/default/lib/spices/spices.cmti"
  "_build/install/default/lib/spices/spices.cmx"
  "_build/install/default/lib/spices/spices.cmxa"
  "_build/install/default/lib/spices/spices.ml"
  "_build/install/default/lib/spices/spices.mli"
  "_build/install/default/lib/spices/spices__.cmi"
  "_build/install/default/lib/spices/spices__.cmt"
  "_build/install/default/lib/spices/spices__.cmx"
  "_build/install/default/lib/spices/spices__.ml"
  "_build/install/default/lib/spices/spices__Formatter.cmi"
  "_build/install/default/lib/spices/spices__Formatter.cmt"
  "_build/install/default/lib/spices/spices__Formatter.cmx"
  "_build/install/default/lib/spices/spices__Gradient.cmi"
  "_build/install/default/lib/spices/spices__Gradient.cmt"
  "_build/install/default/lib/spices/spices__Gradient.cmx"
]
libexec: [
  "_build/install/default/lib/spices/spices.cmxs"
]
doc: [
  "_build/install/default/doc/spices/CHANGES.md"
  "_build/install/default/doc/spices/LICENSE.md"
  "_build/install/default/doc/spices/README.md"
]
